// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// validIntegerCovAndIntegerM
bool validIntegerCovAndIntegerM(IntegerMatrix Cov, IntegerMatrix M);
RcppExport SEXP bsseq_validIntegerCovAndIntegerM(SEXP CovSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Cov(CovSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(validIntegerCovAndIntegerM(Cov, M));
    return __result;
END_RCPP
}
// validIntegerCovAndNumericM
bool validIntegerCovAndNumericM(IntegerMatrix Cov, NumericMatrix M);
RcppExport SEXP bsseq_validIntegerCovAndNumericM(SEXP CovSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Cov(CovSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(validIntegerCovAndNumericM(Cov, M));
    return __result;
END_RCPP
}
// validNumericCovAndIntegerM
bool validNumericCovAndIntegerM(NumericMatrix Cov, IntegerMatrix M);
RcppExport SEXP bsseq_validNumericCovAndIntegerM(SEXP CovSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Cov(CovSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(validNumericCovAndIntegerM(Cov, M));
    return __result;
END_RCPP
}
// validNumericCovAndNumericM
bool validNumericCovAndNumericM(NumericMatrix Cov, NumericMatrix M);
RcppExport SEXP bsseq_validNumericCovAndNumericM(SEXP CovSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Cov(CovSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(validNumericCovAndNumericM(Cov, M));
    return __result;
END_RCPP
}
