# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal helper functions to check that the Cov and M matrix objects in a
#' BSseq object are valid.
#'
#' Equivalent to
#' any(M < 0) || any(M > Cov) || any(is.na(M)) || any(is.na(Cov)) ||
#' any(is.infinite(Cov)) but
#' - **Much** more memory efficient because there are no intermediate vectors
#' - Many times faster when M and Cov are valid (requiring 5 less iterations
#'   over M or Cov and no memory allocations) and many, many times faster if
#'   M or Cov are invalid for any reason (especially so if the invalid element
#'   occurs towards the beginning of M and Cov or is triggered by one of the
#'   later checks, e.g, Inf value in Cov)
#'
#' IMPORTANT: Do not pass DelayedMatrix objects to these functions, they are
#' only valid for matrix objects
#'
#' @param Cov The Cov matrix
#' @param M The M matrix
#'
#' @keywords internal
#'
#' @return TRUE if M and Cov are valid, FALSE otherwise
#'
#' @keywords internal
#'
.validIntegerCovAndIntegerM <- function(Cov, M) {
    .Call('bsseq_validIntegerCovAndIntegerM', PACKAGE = 'bsseq', Cov, M)
}

.validIntegerCovAndNumericM <- function(Cov, M) {
    .Call('bsseq_validIntegerCovAndNumericM', PACKAGE = 'bsseq', Cov, M)
}

.validNumericCovAndIntegerM <- function(Cov, M) {
    .Call('bsseq_validNumericCovAndIntegerM', PACKAGE = 'bsseq', Cov, M)
}

.validNumericCovAndNumericM <- function(Cov, M) {
    .Call('bsseq_validNumericCovAndNumericM', PACKAGE = 'bsseq', Cov, M)
}

